#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
mcp_scaffold.py — 기존 CLI 스크립트를 fastmcp MCP 서버로 감싸는 생성기

jlowin/fastmcp 패턴 차용: 스크립트를 직접 수정하지 않고 subprocess 래퍼
MCP 서버 파일을 생성한다. 생성물은 fastmcp 패키지(pip install fastmcp)가
설치된 환경에서만 실행된다(BYOB — 생성 자체는 의존성 없음).

사용:
    python scripts/mcp_scaffold.py scripts/mask_korean_pii.py \
        --name pii-mask --desc "한국어 PII 마스킹" -o mcp_servers/
    python scripts/mcp_scaffold.py scripts/stamp_evidence.py \
        --name stamp --emit-config   # mcp_config.json 등록 스니펫 출력
"""
from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

SERVER_TEMPLATE = '''#!/usr/bin/env python3
"""{name} — {desc}

Generated by mcp_scaffold.py. wraps: {script}
Requires: pip install fastmcp
"""
import subprocess
import sys
from pathlib import Path

from fastmcp import FastMCP

SCRIPT = Path(__file__).resolve().parents[1] / "{script}"
mcp = FastMCP("{name}")


@mcp.tool
def run_{safe}(arguments: str = "") -> str:
    """{desc} — 인자는 공백 구분 CLI 인자 문자열 (예: "input.txt --json")."""
    cmd = [sys.executable, str(SCRIPT)]
    if arguments.strip():
        cmd += arguments.split()
    proc = subprocess.run(cmd, capture_output=True, text=True, timeout=600)
    out = proc.stdout + ("\\n[stderr] " + proc.stderr if proc.stderr else "")
    return f"exit={{proc.returncode}}\\n{{out}}".format(proc=proc, out=out)


if __name__ == "__main__":
    mcp.run()
'''


def _safe_ident(name: str) -> str:
    """MCP 툴 이름 규약: 소문자/숫자/하이픈/언더스코어, 영문 시작."""
    import re
    if not re.fullmatch(r"[a-z][a-z0-9_-]*", name):
        raise SystemExit(
            f"툴 이름 규약 위반 (소문자 시작, [a-z0-9_-]만 허용): {name}")
    return name.replace("-", "_")


def render_server(script: str, name: str, desc: str) -> str:
    code = SERVER_TEMPLATE.format(
        name=name, desc=desc or f"{script} CLI 래퍼",
        script=script, safe=_safe_ident(name))
    ast.parse(code)  # 생성물이 파싱 가능한 파이썬인지 즉시 검증
    return code


def config_snippet(name: str, server_path: Path) -> dict:
    return {name: {
        "command": "python3",
        "args": [str(server_path)],
        "description": f"fastmcp 서버 — {name}",
    }}


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="CLI 스크립트 → fastmcp 서버 스캐폴드")
    ap.add_argument("script", help="래핑할 CLI 스크립트 (저장소 루트 기준 경로)")
    ap.add_argument("--name", required=True, help="MCP 서버/툴 이름")
    ap.add_argument("--desc", default=None, help="툴 설명")
    ap.add_argument("-o", "--outdir", type=Path, default=Path("mcp_servers"))
    ap.add_argument("--emit-config", action="store_true",
                    help="파일 생성 대신 mcp_config.json 스니펫만 출력")
    args = ap.parse_args(argv)

    script = Path(args.script)
    if not args.emit_config and not script.exists():
        print(f"스크립트가 없습니다: {script}", file=sys.stderr)
        return 2

    code = render_server(args.script, args.name, args.desc)
    server_path = args.outdir / f"{args.name}_server.py"

    if args.emit_config:
        import json
        print(json.dumps(config_snippet(args.name, server_path),
                         ensure_ascii=False, indent=2))
        return 0

    args.outdir.mkdir(parents=True, exist_ok=True)
    server_path.write_text(code, encoding="utf-8")
    print(f"생성 → {server_path}")
    print("등록: mcp_config.json에 아래 항목 추가")
    import json
    print(json.dumps(config_snippet(args.name, server_path),
                     ensure_ascii=False, indent=2))
    print("실행 요건: pip install fastmcp")
    return 0


if __name__ == "__main__":
    sys.exit(main())
